USE demo;
CREATE TABLE users (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) UNIQUE,
    password VARCHAR(255),
    name VARCHAR(255),
    u2f TINYINT UNSIGNED DEFAULT 0 NOT NULL,
    totp TINYINT UNSIGNED DEFAULT 0 NOT NULL,
    admin TINYINT UNSIGNED DEFAULT 0 NOT NULL
);
